const CFG=window.POPPAD_ORDER_CONFIG||{};
const CATALOG={
 coffee:{label:'Coffee',icon:'☕',items:[
  {id:'americano',name:'Americano',price:3.20,coffee:true},{id:'latte',name:'Latte',price:3.80,coffee:true},{id:'cappuccino',name:'Cappuccino',price:3.80,coffee:true},{id:'flat-white',name:'Flat White',price:3.60,coffee:true},{id:'espresso',name:'Espresso',price:2.70,coffee:true,noMilk:true},{id:'mocha',name:'Mocha',price:4.20,coffee:true},{id:'hot-chocolate',name:'Hot Chocolate',price:4.00,coffee:true}
 ]},
 cold:{label:'Cold Drinks',icon:'🧊',items:[
  {id:'iced-americano',name:'Iced Americano',price:3.50,coffee:true},{id:'iced-latte',name:'Iced Latte',price:4.20,coffee:true},{id:'iced-mocha',name:'Iced Mocha',price:4.50,coffee:true},{id:'water',name:'Bottled Water',price:2.00},{id:'orange-juice',name:'Orange Juice',price:2.80},{id:'coca-cola',name:'Coca-Cola',price:2.50},{id:'coke-zero',name:'Coke Zero',price:2.50},{id:'7up',name:'7UP',price:2.50}
 ]},
 breakfast:{label:'Breakfast',icon:'🍳',items:[
  {id:'breakfast-bap',name:'Breakfast Bap',price:6.50,type:'bap'},{id:'overnight-oats',name:'Overnight Oats',price:5.50,type:'oats'},{id:'croissant',name:'Croissant',price:3.20,type:'croissant'},{id:'pain-au-chocolat',name:'Pain au Chocolat',price:3.50},{id:'sourdough',name:'Toasted Sourdough',price:4.50,type:'sourdough'}
 ]},
 snacks:{label:'Snacks',icon:'🍪',items:[
  {id:'protein-balls',name:'Protein Balls',price:3.50},{id:'protein-bar',name:'Protein Bar',price:3.00},{id:'muffin',name:'Muffin',price:3.20},{id:'cookie',name:'Cookie',price:2.80}
 ]}
};
let basket=[],view='home',category=null,current=null,qty=1,selections={},lastActivity=Date.now();
const money=n=>'€'+Number(n).toFixed(2); const app=document.getElementById('app');
function touch(){lastActivity=Date.now()} document.addEventListener('pointerdown',touch);document.addEventListener('keydown',touch);
setInterval(()=>{if(Date.now()-lastActivity>(CFG.inactivityResetMs||90000)){basket=[];view='home';category=null;current=null;render();touch()}},5000);
function header(back=false){return `<header class="top"><div class="brand">poppad<span>CAFÉ</span></div>${back?'<button class="back" onclick="goBack()">← Back</button>':`<button class="cartbtn" onclick="showBasket()">Basket (${basket.reduce((s,x)=>s+x.qty,0)})</button>`}</header>`}
function render(){if(view==='home')home();else if(view==='category')cat();else if(view==='product')product();else if(view==='basket')basketView();else if(view==='checkout')checkout();}
function home(){app.innerHTML=header()+`<section class="hero"><h1>Good food.<br>Great days.</h1><p>Fresh coffee, delicious food and a warm welcome. Order here, then pay at the counter when collecting.</p></section><section class="content"><h2 class="section-title">Our Menu</h2><div class="grid">${Object.entries(CATALOG).map(([k,c])=>`<div class="card category" onclick="openCat('${k}')"><div class="icon">${c.icon}</div><h3>${c.label} →</h3></div>`).join('')}</div></section>${foot()}`}
function openCat(k){category=k;view='category';render()} function cat(){let c=CATALOG[category];app.innerHTML=header(true)+`<section class="content"><h2 class="section-title">${c.icon} ${c.label}</h2><div class="grid">${c.items.map(i=>`<div class="card product" onclick="openProduct('${i.id}')"><h3>${i.name}</h3><div class="price">${money(i.price)}</div></div>`).join('')}</div></section>${foot()}`}
function findItem(id){for(const c of Object.values(CATALOG)){const x=c.items.find(i=>i.id===id);if(x)return x}}
function openProduct(id){current=findItem(id);qty=1;selections={size:'Regular',milk:'Whole Milk',syrup:'No Syrup',extras:[],sauce:'No Sauce',topping:'Mixed Berries',choice:'Plain'};view='product';render()}
function chips(group,vals,multi=false){return `<div class="options">${vals.map(v=>{const label=typeof v==='string'?v:v[0],add=typeof v==='string'?0:v[1],on=multi?selections[group].includes(label):selections[group]===label;return `<button class="chip ${on?'on':''}" onclick="pick('${group}','${label.replaceAll("'","\\'")}',${multi})">${label}${add?` +${money(add)}`:''}</button>`}).join('')}</div>`}
function pick(g,v,multi){if(multi){const a=selections[g];const n=a.indexOf(v);n>=0?a.splice(n,1):a.push(v)}else selections[g]=v;render()}
function optionPrice(){let p=0;if(selections.size==='Large')p+=.5;if(['Oat Milk','Almond Milk'].includes(selections.milk))p+=.5;if(selections.syrup!=='No Syrup')p+=.5;const extras={ 'Extra Shot':.7,'Extra Bacon':1,'Extra Sausage':1,'Extra Egg':1,'Cheese':.7,'Extra Berries':.7,'Extra Banana':.5,'Peanut Butter':.7,'Honey':.5,'Extra Avocado':1,'Bacon':1,'Ham & Cheese':2};(selections.extras||[]).forEach(x=>p+=(extras[x]||0));return p}
function product(){let i=current,html='';if(i.coffee){html+=`<div class="option-group"><h3>Size</h3>${chips('size',[['Regular',0],['Large',.5]])}</div>`;if(!i.noMilk)html+=`<div class="option-group"><h3>Milk</h3>${chips('milk',[['Whole Milk',0],['Low-Fat Milk',0],['Oat Milk',.5],['Almond Milk',.5]])}</div>`;html+=`<div class="option-group"><h3>Syrup</h3>${chips('syrup',[['No Syrup',0],['Vanilla',.5],['Caramel',.5],['Hazelnut',.5]])}</div><div class="option-group"><h3>Extras</h3>${chips('extras',[['Extra Shot',.7]],true)}</div>`}
if(i.type==='bap')html+=`<div class="notice">Includes Bacon • Sausage • Egg</div><div class="option-group"><h3>Extras</h3>${chips('extras',[['Extra Bacon',1],['Extra Sausage',1],['Extra Egg',1],['Cheese',.7]],true)}</div><div class="option-group"><h3>Sauce</h3>${chips('sauce',['Ketchup','Brown Sauce','No Sauce'])}</div>`;
if(i.type==='oats')html+=`<div class="option-group"><h3>Choose a topping</h3>${chips('topping',['Mixed Berries','Banana','Peanut Butter'])}</div><div class="option-group"><h3>Extras</h3>${chips('extras',[['Extra Berries',.7],['Extra Banana',.5],['Peanut Butter',.7],['Honey',.5]],true)}</div>`;
if(i.type==='croissant')html+=`<div class="option-group"><h3>Choose</h3>${chips('choice',['Plain','Butter','Jam'])}</div><div class="option-group"><h3>Extra</h3>${chips('extras',[['Ham & Cheese',2]],true)}</div>`;
if(i.type==='sourdough')html+=`<div class="option-group"><h3>Choose</h3>${chips('choice',['Avocado','Scrambled Egg','Ham & Cheese'])}</div><div class="option-group"><h3>Extras</h3>${chips('extras',[['Extra Egg',1],['Extra Avocado',1],['Bacon',1]],true)}</div>`;
let each=i.price+optionPrice();app.innerHTML=header(true)+`<section class="content"><h2 class="section-title">${i.name}</h2><div class="price">From ${money(i.price)}</div>${html}<div class="qty"><button class="chip" onclick="changeQty(-1)">−</button><strong>${qty}</strong><button class="chip" onclick="changeQty(1)">+</button></div><button class="primary" onclick="addToBasket()">ADD TO ORDER • ${money(each*qty)}</button></section>${foot()}`}
function changeQty(n){qty=Math.max(1,Math.min(10,qty+n));render()}
function desc(i){let a=[];if(i.coffee){a.push(selections.size);if(!i.noMilk)a.push(selections.milk);if(selections.syrup!=='No Syrup')a.push(selections.syrup)}if(i.type==='bap')a.push(selections.sauce);if(i.type==='oats')a.push(selections.topping);if(['croissant','sourdough'].includes(i.type))a.push(selections.choice);a.push(...(selections.extras||[]));return a.filter(Boolean)}
function addToBasket(){basket.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),itemId:current.id,name:current.name,qty,unit:current.price+optionPrice(),options:desc(current)});view='basket';render()}
function showBasket(){view='basket';render()} function basketTotal(){return basket.reduce((s,x)=>s+x.unit*x.qty,0)}
function basketView(){app.innerHTML=header(true)+`<section class="content"><h2 class="section-title">Your Order</h2>${basket.length?basket.map(x=>`<div class="basket-item"><div><strong>${x.qty} × ${x.name}</strong><div class="muted">${x.options.join(' • ')||'Standard'}</div><button class="chip" style="margin-top:8px" onclick="removeItem('${x.id}')">Remove</button></div><strong>${money(x.unit*x.qty)}</strong></div>`).join(''):'<div class="notice">Your basket is empty.</div>'}${basket.length?`<div class="total"><span>Total</span><span>${money(basketTotal())}</span></div><button class="secondary" onclick="view='home';render()">ADD MORE ITEMS</button><br><br><button class="primary" onclick="view='checkout';render()">CHECKOUT</button>`:`<button class="primary" onclick="view='home';render()">BROWSE MENU</button>`}</section>${foot()}`}
function removeItem(id){basket=basket.filter(x=>x.id!==id);render()} function goBack(){if(view==='product'){view='category'}else if(view==='category'){view='home'}else if(view==='basket'){view='home'}else if(view==='checkout'){view='basket'}render()}
function checkout(){app.innerHTML=header(true)+`<section class="content"><h2 class="section-title">Checkout</h2><div class="total"><span>Total</span><span>${money(basketTotal())}</span></div><label><strong>Your name</strong></label><input id="custName" class="field" maxlength="40" autocomplete="off" placeholder="Enter your name"><div id="err" class="error"></div><button id="placeBtn" class="primary" onclick="placeOrder()">PLACE ORDER</button><div class="notice">Please pay at the counter when collecting your order.</div></section>${foot()}`}
async function placeOrder(){const name=document.getElementById('custName').value.trim(),err=document.getElementById('err'),btn=document.getElementById('placeBtn');if(!name){err.textContent='Please enter your name.';return}if(!basket.length){err.textContent='Your basket is empty.';return}if(!CFG.orderApiUrl){err.textContent='Demo build: connect a POPPAD CAFÉ backend before live order sending.';return}btn.disabled=true;btn.textContent='SENDING…';try{const r=await fetch(CFG.orderApiUrl,{method:'POST',body:JSON.stringify({action:'placeOrder',name,items:basket.map(x=>({itemId:x.itemId,quantity:x.qty,options:x.options})),total:basketTotal()})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Order failed');success(name,d.orderNumber)}catch(e){err.textContent=e.message;btn.disabled=false;btn.textContent='PLACE ORDER'}}
function success(name,num){basket=[];app.innerHTML=header()+`<section class="success"><div class="tick">✓</div><h1>Thanks, ${escapeHtml(name)}!</h1><p>Your order has been sent to the POPPAD CAFÉ counter.</p><div class="order-no">Order #${escapeHtml(num)}</div><p>Please pay at the counter when collecting your order.</p><button class="primary" onclick="view='home';render()">ORDER MORE ITEMS</button></section>${foot()}`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function foot(){return '<footer class="footer">Digital Ordering by poppad</footer>'} render();
