const POPPAD_ORDER_CONFIG={businessName:"POPPAD CAFÉ"};
const CATALOG={
 "americano":{n:"Americano",p:3.20},"latte":{n:"Latte",p:3.80},"cappuccino":{n:"Cappuccino",p:3.80},"flat-white":{n:"Flat White",p:3.60},"espresso":{n:"Espresso",p:2.70},"mocha":{n:"Mocha",p:4.20},"hot-chocolate":{n:"Hot Chocolate",p:4.00},
 "iced-americano":{n:"Iced Americano",p:3.50},"iced-latte":{n:"Iced Latte",p:4.20},"iced-mocha":{n:"Iced Mocha",p:4.50},"water":{n:"Bottled Water",p:2.00},"orange-juice":{n:"Orange Juice",p:2.80},"coca-cola":{n:"Coca-Cola",p:2.50},"coke-zero":{n:"Coke Zero",p:2.50},"7up":{n:"7UP",p:2.50},
 "breakfast-bap":{n:"Breakfast Bap",p:6.50},"overnight-oats":{n:"Overnight Oats",p:5.50},"croissant":{n:"Croissant",p:3.20},"pain-au-chocolat":{n:"Pain au Chocolat",p:3.50},"sourdough":{n:"Toasted Sourdough",p:4.50},"protein-balls":{n:"Protein Balls",p:3.50},"protein-bar":{n:"Protein Bar",p:3.00},"muffin":{n:"Muffin",p:3.20},"cookie":{n:"Cookie",p:2.80}
};
const ADDONS={"Large":.5,"Oat Milk":.5,"Almond Milk":.5,"Vanilla":.5,"Caramel":.5,"Hazelnut":.5,"Extra Shot":.7,"Extra Bacon":1,"Extra Sausage":1,"Extra Egg":1,"Cheese":.7,"Extra Berries":.7,"Extra Banana":.5,"Peanut Butter":.7,"Honey":.5,"Extra Avocado":1,"Bacon":1,"Ham & Cheese":2};
function doGet(e){const a=e&&e.parameter&&e.parameter.action||"";if(a==="orders")return json_({ok:true,orders:active_()});return json_({ok:true,system:"POPPAD ORDER",business:POPPAD_ORDER_CONFIG.businessName,status:"READY"})}
function doPost(e){try{const d=JSON.parse(e.postData.contents||"{}");if((d.action||"placeOrder")==="placeOrder")return place_(d);if(d.action==="completeOrder")return complete_(d.orderId);return json_({ok:false,error:"Unknown action."})}catch(x){return json_({ok:false,error:x.message})}}
function place_(d){const name=clean_(d.name);if(!name)throw Error("Invalid customer name.");if(!Array.isArray(d.items)||!d.items.length||d.items.length>30)throw Error("Invalid basket.");let total=0,items=d.items.map(x=>{const c=CATALOG[clean_(x.itemId)];if(!c)throw Error("Unknown menu item.");const q=Number(x.quantity);if(!Number.isInteger(q)||q<1||q>10)throw Error("Invalid quantity.");const opts=Array.isArray(x.options)?x.options.map(clean_):[];let unit=c.p;opts.forEach(o=>unit+=(ADDONS[o]||0));total+=unit*q;return{itemId:clean_(x.itemId),itemName:c.n,quantity:q,options:opts,unitPrice:round_(unit)}});total=round_(total);if(Math.abs(Number(d.total)-total)>.009)throw Error("Order total did not validate. Please review the basket.");const lock=LockService.getScriptLock();lock.waitLock(10000);try{const p=PropertiesService.getScriptProperties(),n=Number(p.getProperty("NEXT_ORDER_NUMBER")||"1"),id=Utilities.getUuid(),o={id:id,orderNumber:String(n).padStart(3,"0"),customerName:name,items:items,total:total,status:"ACTIVE",createdAt:new Date().toISOString()};p.setProperty("NEXT_ORDER_NUMBER",String(n+1));p.setProperty("ORDER_"+id,JSON.stringify(o));return json_({ok:true,orderNumber:o.orderNumber})}finally{lock.releaseLock()}}
function active_(){const a=PropertiesService.getScriptProperties().getProperties(),out=[];Object.keys(a).forEach(k=>{if(k.indexOf("ORDER_")===0){try{const o=JSON.parse(a[k]);if(o.status==="ACTIVE")out.push(o)}catch(e){}}});out.sort((x,y)=>new Date(x.createdAt)-new Date(y.createdAt));return out}
function complete_(id){const p=PropertiesService.getScriptProperties(),k="ORDER_"+clean_(id),s=p.getProperty(k);if(!s)return json_({ok:false,error:"Order not found."});const o=JSON.parse(s);o.status="COMPLETE";o.completedAt=new Date().toISOString();p.setProperty(k,JSON.stringify(o));return json_({ok:true})}
function clean_(v){return String(v||"").trim().substring(0,80)}function round_(n){return Math.round(n*100)/100}function json_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}
